#ifndef _N_N_ERRORS_INCLUDED
#define _N_N_ERRORS_INCLUDED

#define ERROR_NEURON_NULL_REFERENCE 1001;
#define ERROR_NEURON_BAD_CONNECTION 1002;
#define ERROR_NEURON_NULL_A_FUNCTION 1003;
#define ERROR_NEURON_WRONG_METHOD 1004;

#define ERROR_NN_WORK_WITH_FILE 1004;

#endif //_N_N_ERRORS_INCLUDED
